# Remap media keys to seek backward/forward 3 seconds in the video.
# These are typically bound to the "Previous Track" and "Next Track" buttons on a keyboard.
# WARNING: KEEP IN MIND THAT THIS APPLIES TO MEDIA BUTTONS ON THE KEYBOARD, 
# NOT TO REGULAR > AND < ARROW KEYS ON THE KEYBOARD, THESE WILL JUMP 5 SEC
PREV seek -3
NEXT seek +3

# Seek backward/forward by 3 seconds using arrow keys
# WARNING: THIS IS ACTUALLY FOR ARROW BUTTONS ON THE KEYBOARD, NOT FOR MEDIA KEYS
LEFT seek -3
RIGHT seek +3
