// This file is auto-generated by dataFactory.ts
export const testString = "Hello World! {\"key\": \"value\", \"arr\": [1, 2, 3]} ? & ,";
export const transformedString = "Hello.World\".(!key!-.!value!*.!arr!-.[1*.2*.3])._.~.*";
export const iterations = 1000000;
