/*
 * ============================================================================
 * dataFactory.ts
 * ============================================================================
 * 
 * This script generates a fresh `data.js` file from standard input.
 * It reads the entire input from stdin, safely serializes it, and writes
 * it out as `testString` alongside the `iterations` count into `data.js`.
 * 
 * Usage Examples:
 * 
 * 1. Using echo:
 *    echo "My custom test string" | npx tsx dataFactory.ts
 * 
 * 2. Using a file:
 *    cat somefile.txt | npx tsx dataFactory.ts
 * 
 * 3. With custom iterations (optional second argument):
 *    echo "Testing 123" | npx tsx dataFactory.ts 5000000
 * ============================================================================
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

let inputData = '';

process.stdin.setEncoding('utf-8');

process.stdin.on('data', (chunk) => {
    inputData += chunk;
});

process.stdin.on('end', async () => {
    // Trim trailing newline often added by echo
    const cleanInput = inputData.replace(/\n$/, '');
    
    // Fallback to default if entirely empty
    const rawString = cleanInput || 'Hello World! {"key": "value", "arr": [1, 2, 3]} ? & ,';
    
    // Parse iterations from CLI argument, default to 1,000,000
    const iterationsArg = process.argv[2];
    const iterations = parseInt(iterationsArg, 10) || 1000000;

    // Use v1.js by default, or accept another version via CLI
    const versionArg = process.argv[3] || 'v1.js';
    let flipget;
    try {
        const modulePath = `file://${path.join(__dirname, 'versions', versionArg)}`;
        const module = await import(modulePath);
        flipget = module.default;
    } catch (e) {
        console.error(`❌ Failed to load version ${versionArg}:`, e.message);
        process.exit(1);
    }

    // Transform the string using the selected implementation
    const transformedString = flipget(rawString);

    const targetFile = path.join(__dirname, 'data.js');

    // JSON.stringify safely escapes quotes, newlines, and special characters
    const content = `// This file is auto-generated by dataFactory.ts
export const testString = ${JSON.stringify(rawString)};
export const transformedString = ${JSON.stringify(transformedString)};
export const iterations = ${iterations};
`;

    fs.writeFileSync(targetFile, content, 'utf-8');
    console.log(`✅ data.js generated successfully using ${versionArg}! String length: ${rawString.length}, Iterations: ${iterations}`);
});
