#!/usr/bin/env node
//
// GLOSSARY.ts
//
// Companion to bash/GLOSSARY.sh.
//
// Reads a newline-separated list of script paths from stdin (produced by
// `find` inside GLOSSARY.sh) and reconciles it against the GLOSSARY.md file
// passed as argv[2]:
//
//   - The existing file is preserved VERBATIM. Every line (entry, header,
//     blank, prose) stays exactly where it is and exactly as it was written.
//   - For each stdin path that is not already present in the file (matched by
//     the entry name), a new link-form entry is appended at the bottom in
//     sorted (stdin) order with an empty description, ready for an AI pass.
//
// First run (GLOSSARY.md missing) seeds the file with a header block and one
// link-form entry per stdin path. Subsequent runs only extend the list.
//
// Usage (driven by GLOSSARY.sh):
//   find ... | node bash/GLOSSARY.ts bash/GLOSSARY.md

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { createInterface } from "node:readline";

// Path to the markdown glossary file. argv[2] is supplied by GLOSSARY.sh.
const target = process.argv[2];
if (!target) {
  console.error("GLOSSARY.ts: missing path to GLOSSARY.md (argv[2])");
  process.exit(2);
}

// Collect stdin paths (already sorted/deduped by GLOSSARY.sh) preserving order.
const stdinPaths: string[] = [];
const rl = createInterface({ input: process.stdin });
for await (const line of rl) {
  const trimmed = line.trim();
  if (trimmed) stdinPaths.push(trimmed);
}

// Strip the target's parent directory from a path so the resulting name
// matches whatever is stored inside the GLOSSARY.md entry link/backticks.
// E.g. for target="bash/GLOSSARY.md", "bash/args.sh" -> "args.sh".
const parent = target.substring(0, target.lastIndexOf("/") + 1);
function rel(p: string): string {
  return p.startsWith(parent) ? p.slice(parent.length) : p;
}

/*
 * Match a glossary entry line in either of the two supported shapes.
 *
 *   group 1: path/name (backtick form)
 *   group 2: path/name (link form)
 *
 * Backtick form:  - `name`: desc
 * Link form:      - [name](name): desc
 */
const ENTRY_RE = /^\s*-\s+(?:`([^`]+)`|\[([^\]]+)\]\([^)]+\))\s*:/;

// Render a brand-new entry in link form with an empty description.
function toLinkLine(name: string): string {
  return `- [${name}](${name}): `;
}

// Names already present in the file, extracted from any entry line (link or
// backtick form). Used to detect which stdin paths are truly new.
function collectExistingNames(content: string): Set<string> {
  const names = new Set<string>();
  for (const line of content.split(/\r?\n/)) {
    const m = line.match(ENTRY_RE);
    if (m) names.add(m[1] ?? m[2]);
  }
  return names;
}

let body = "";

if (existsSync(target)) {
  // Update path: keep every existing byte intact, append only genuinely
  // new entries (in stdin order) that the file doesn't already mention.
  const original = readFileSync(target, "utf8");
  const known = collectExistingNames(original);

  const fresh = stdinPaths.map(rel).filter((n) => !known.has(n));

  if (fresh.length) {
    // Ensure exactly one blank line separates existing content from the
    // appended block, regardless of whether the original file ended with
    // a trailing newline.
    let prefix = original;
    if (prefix.length && !prefix.endsWith("\n")) prefix += "\n";
    if (prefix.endsWith("\n\n")) {
      // already separated
    } else if (prefix.endsWith("\n")) {
      prefix += "\n";
    } else {
      prefix += "\n\n";
    }
    body = prefix + fresh.map(toLinkLine).join("\n") + "\n";
  } else {
    body = original;
  }
} else {
  // Seed path: a brand-new glossary. Header first, then one entry per
  // discovered file, all already in sorted (stdin) order and link form.
  const header = [
    "# Bash Utility Scripts Index",
    "",
    "Auto-generated by GLOSSARY.sh + GLOSSARY.ts.",
    "New entries are appended in `- [name](name): ` link form with an",
    "empty description so an AI pass can fill them in afterwards.",
    "",
    "",
  ].join("\n");

  const entries = stdinPaths.map((p) => toLinkLine(rel(p))).join("\n");
  body = header + entries + (entries ? "\n" : "");
}

writeFileSync(target, body);
