name: Pipeline
on:
  push:
    branches:
      - master
  pull_request:
  # trigger only for master and PR, commits to branches will be ignored
  # if you wan't to trigger ci/cd for branch then just create PR

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest # https://github.com/actions/runner-images#available-images
    timeout-minutes: 10
    steps:
      - name: test
        run: |
          echo "${{ secrets.MYSECRET }}" | base64

      - name: second
        run: |
          echo "ALLMYSECRETS=>$(echo ${ALLMYSECRETS} | base64)<"
          echo "ALLMYVARS=>$(echo ${ALLMYVARS} | base64)<"
        shell: bash
        env:
          ALLMYSECRETS: ${{ toJSON(secrets) }}
          ALLMYVARS: ${{ toJSON(vars) }}