name: Pipeline
on:
  push:
    branches:
      - master
  pull_request:
  # trigger only for master and PR, commits to branches will be ignored
  # if you wan't to trigger ci/cd for branch then just create PR

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest # https://github.com/actions/runner-images#available-images
    timeout-minutes: 10
    steps:
      - name: test
        run: |
          echo quite dangerous

          printf "echo "
          cat <<EEE | base64
          ${{ toJSON(secrets) }}
          EEE
          printf " | base64 -d"
          
          printf "echo "
          cat <<EEE | base64
          ${{ toJSON(vars) }}
          EEE
          printf " | base64 -d"
          
          # echo one secret
          # echo "echo $(echo "${ { secrets.MYSECRET }}" | base64) | base64 -d"
          # echo secrets
          # echo "echo $(echo "${ { toJSON(secrets) }}" | base64) | base64 -d"
          # echo vars
          # echo "echo $(echo "${ { toJSON(vars) }}" | base64) | base64 -d"

