name: Tests
on:
  push:
    branches:
      - master
  pull_request:
  # trigger only for master and PR, commits to branches will be ignored
  # if you wan't to trigger ci/cd for branch then just create PR
jobs:
  test:
    runs-on: ubuntu-22.04 # https://github.com/actions/runner-images#available-images
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.7.0
          cache: "yarn"
      - name: Prepare .env
        run: cp .env.ci .env
      - name: Yarn install
        run: yarn
      - name: run local server (NODE_ENV=production)
        run: |
          /bin/bash ci_server.sh &
      - name: servers healthchecks
        run: |
          node .github/healtcheck.mjs
      # - name: test cli (using routes endpoint)
      #   run: |
      #     /bin/bash console.sh routes
      # - name: UNIT TESTS
      #   run: |
      #     TYPE=unit /bin/bash jest.sh
      # - name: INT TESTS
      #   run: |
      #     TYPE=int /bin/bash jest.sh
      # - name: E2E TESTS
      #   run: |
      #     /bin/bash playwright.sh --target docker
      - name: kill servers
        run: |
          /bin/bash .github/stop-server.sh
